services:
  - type: web
    name: eventplanner-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python voterbot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
